In [1]:
import pandas as pd
import numpy as np

In [3]:
data = pd.read_csv("E:\\celebal internship\\week 1\\datas\\archive\\Combined_dataset.csv")

In [4]:
data

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,...,amount_of_stars,what_customers_said,seller_name,sizes,videos,seller_information,variations,best_offer,more_offers,category
0,8376765,Lino Perros,Women Navy Blue Solid Backpack,3.8,15,3995,58.0,"""₹3,995.00""",INR,http://assets.myntassets.com/assets/images/837...,...,"{""1_star"":2,""2_stars"":0,""3_stars"":3,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]","[""rw-8376765_cae700""]",NaN,[{}],{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
1,9136281,Tommy Hilfiger,Unisex Navy Blue Striped Backpack,4.5,67,2899,35.0,"""₹2,899.00""",INR,http://assets.myntassets.com/assets/images/913...,...,"{""1_star"":3,""2_stars"":4,""3_stars"":2,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]","[""rw-9136281_cae700""]",NaN,"[{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
2,17633752,Lavie,Aries Women Pink Mini Backpack,4.4,226,2999,65.0,"""₹2,999.00""",INR,http://assets.myntassets.com/assets/images/176...,...,"{""1_star"":9,""2_stars"":5,""3_stars"":10,""4_stars""...",NaN,NaN,"[{""size"":""S""}]","[""https://videos.myntassets.com/assets/videos/...",NaN,"[{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
3,1376949,F Gear,Unisex Navy & Grey Printed Burner Backpack,4.4,1052,1675,52.0,"""₹1,675.00""",INR,http://assets.myntassets.com/assets/images/137...,...,"{""1_star"":33,""2_stars"":21,""3_stars"":69,""4_star...",NaN,NaN,"[{""size"":""Onesize""}]","[""https://videos.myntassets.com/assets/videos/...",NaN,NaN,{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
4,13939916,MYTRIDENT,Men Blue Solid Bath Robe,4.7,12,2899,17.0,"""₹2,899.00""",INR,http://assets.myntassets.com/assets/images/pro...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",NaN,NaN,"[{""size"":""M"",""value"":""45.0in"",""value_name"":""Fr...",NaN,NaN,"[{},{},{},{},{},{},{},{},{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on IndusI...",bath-robe
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,13698258,KREDO,Men FORTE Silver Automatic Skeleton Analogue W...,3.5,11,11890,50.0,"""₹11,890.00""",INR,http://assets.myntassets.com/assets/images/136...,...,"{""1_star"":3,""2_stars"":0,""3_stars"":2,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]","[""pi-13698258""]",NaN,NaN,{},"[{""offer_name"":""10% Instant Discount on Citi C...",watches
996,16896006,GUESS,Women White Patterned Dial & White Straps Anal...,5.0,22,8900,45.0,"""₹8,900.00""",INR,http://assets.myntassets.com/assets/images/168...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]","[""rw-16896006_cae700"",""https://videos.myntasse...",NaN,NaN,{},"[{""offer_name"":""10% Instant Discount on Citi C...",watches
997,1708108,GIORDANO,Women Rose Gold-Toned Mirrored Analogue Watch ...,2.8,5,7950,50.0,"""₹7,950.00""",INR,http://assets.myntassets.com/assets/images/170...,...,"{""1_star"":2,""2_stars"":1,""3_stars"":0,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]",NaN,NaN,"[{},{},{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",watches
998,19280114,Fastrack,Men Black Brass Dial & Black Stainless Steel S...,4.3,17,3295,20.0,"""₹2,636.00""",INR,http://assets.myntassets.com/assets/images/192...,...,"{""1_star"":1,""2_stars"":2,""3_stars"":0,""4_stars"":...",NaN,Tru███m R███il,"[{""size"":""Onesize""}]",NaN,Sho███o. ███-10█████████enu███████████████████...,NaN,"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",watches
999,18601682,BOLDFIT,Purple Textured Yoga Mat,3.8,161,699,31.0,"""₹699.00""",INR,http://assets.myntassets.com/assets/images/186...,...,"{""1_star"":24,""2_stars"":8,""3_stars"":22,""4_stars...",NaN,NaN,"[{""size"":""Medium""}]",NaN,NaN,"[{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",yoga-mats

In [23]:
data.head(10)

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,...,amount_of_stars,what_customers_said,seller_name,sizes,videos,seller_information,variations,best_offer,more_offers,category
0,8376765,Lino Perros,Women Navy Blue Solid Backpack,3.8,15,3995,58.0,"""₹3,995.00""",INR,http://assets.myntassets.com/assets/images/837...,...,"{""1_star"":2,""2_stars"":0,""3_stars"":3,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]","[""rw-8376765_cae700""]",NaN,[{}],{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
1,9136281,Tommy Hilfiger,Unisex Navy Blue Striped Backpack,4.5,67,2899,35.0,"""₹2,899.00""",INR,http://assets.myntassets.com/assets/images/913...,...,"{""1_star"":3,""2_stars"":4,""3_stars"":2,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]","[""rw-9136281_cae700""]",NaN,"[{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
2,17633752,Lavie,Aries Women Pink Mini Backpack,4.4,226,2999,65.0,"""₹2,999.00""",INR,http://assets.myntassets.com/assets/images/176...,...,"{""1_star"":9,""2_stars"":5,""3_stars"":10,""4_stars""...",NaN,NaN,"[{""size"":""S""}]","[""https://videos.myntassets.com/assets/videos/...",NaN,"[{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
3,1376949,F Gear,Unisex Navy & Grey Printed Burner Backpack,4.4,1052,1675,52.0,"""₹1,675.00""",INR,http://assets.myntassets.com/assets/images/137...,...,"{""1_star"":33,""2_stars"":21,""3_stars"":69,""4_star...",NaN,NaN,"[{""size"":""Onesize""}]","[""https://videos.myntassets.com/assets/videos/...",NaN,NaN,{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
4,13939916,MYTRIDENT,Men Blue Solid Bath Robe,4.7,12,2899,17.0,"""₹2,899.00""",INR,http://assets.myntassets.com/assets/images/pro...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",NaN,NaN,"[{""size"":""M"",""value"":""45.0in"",""value_name"":""Fr...",NaN,NaN,"[{},{},{},{},{},{},{},{},{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on IndusI...",bath-robe
5,17198778,H&M,Beige & Tan Solid Stoneware Soap Dispenser,4.5,42,1399,NaN,"""₹1,399.00""",INR,http://assets.myntassets.com/assets/images/171...,...,"{""1_star"":2,""2_stars"":2,""3_stars"":0,""4_stars"":...",NaN,H &███Hen███ & █████████eta█████████████████████,"[{""size"":""Onesize""}]",NaN,Pra███yat███fra█████████PVT███████████████████...,"[{},{}]","{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",bathroom-accessories
6,19851824,AVI Living,Grey Solid 500 GSM Pure Cotton Bath Towel,4.0,5,1399,65.0,"""₹1,399.00""",INR,http://assets.myntassets.com/assets/images/198...,...,"{""1_star"":0,""2_stars"":1,""3_stars"":0,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]",NaN,NaN,"[{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",bath-towels
7,18602872,My Room,Yellow & Green Floral 140 TC King Bedsheet wit...,4.7,10,2999,54.0,"""₹2,999.00""",INR,http://assets.myntassets.com/assets/images/186...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",NaN,NaN,"[{""size"":""Single""},{""size"":""Double Queen""},{""s...",NaN,NaN,[{}],{},"[{""offer_name"":""10% Instant Discount on Citi C...",bedsheets
8,18602850,My Room,Ethnic Print 144 TC Super King Bedsheet with 2...,4.5,22,2999,54.0,"""₹2,999.00""",INR,http://assets.myntassets.com/assets/images/186...,...,"{""1_star"":1,""2_stars"":1,""3_stars"":1,""4_stars"":...",NaN,NaN,"[{""size"":""Super King""}]",NaN,NaN,[{}],{},"[{""offer_name"":""10% Instant Discount on Citi C...",bedsheets
9,8961147,Story@home,Pink & White Floral 160 TC Cotton 1 King Bedsh...,3.7,7,2199,53.0,"""₹2,199.00""",INR,http://assets.myntassets.com/assets/images/896...,...,"{""1_star"":1,""2_stars"":1,""3_stars"":0,""4_stars"":...",NaN,NaN,"[{""size"":""Double King""}]",NaN,NaN,"[{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",bedsheets

In [24]:
data.tail()

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,...,amount_of_stars,what_customers_said,seller_name,sizes,videos,seller_information,variations,best_offer,more_offers,category
995,13698258,KREDO,Men FORTE Silver Automatic Skeleton Analogue W...,3.5,11,11890,50.0,"""₹11,890.00""",INR,http://assets.myntassets.com/assets/images/136...,...,"{""1_star"":3,""2_stars"":0,""3_stars"":2,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]","[""pi-13698258""]",NaN,NaN,{},"[{""offer_name"":""10% Instant Discount on Citi C...",watches
996,16896006,GUESS,Women White Patterned Dial & White Straps Anal...,5.0,22,8900,45.0,"""₹8,900.00""",INR,http://assets.myntassets.com/assets/images/168...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]","[""rw-16896006_cae700"",""https://videos.myntasse...",NaN,NaN,{},"[{""offer_name"":""10% Instant Discount on Citi C...",watches
997,1708108,GIORDANO,Women Rose Gold-Toned Mirrored Analogue Watch ...,2.8,5,7950,50.0,"""₹7,950.00""",INR,http://assets.myntassets.com/assets/images/170...,...,"{""1_star"":2,""2_stars"":1,""3_stars"":0,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]",NaN,NaN,"[{},{},{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",watches
998,19280114,Fastrack,Men Black Brass Dial & Black Stainless Steel S...,4.3,17,3295,20.0,"""₹2,636.00""",INR,http://assets.myntassets.com/assets/images/192...,...,"{""1_star"":1,""2_stars"":2,""3_stars"":0,""4_stars"":...",NaN,Tru███m R███il,"[{""size"":""Onesize""}]",NaN,Sho███o. ███-10█████████enu███████████████████...,NaN,"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",watches
999,18601682,BOLDFIT,Purple Textured Yoga Mat,3.8,161,699,31.0,"""₹699.00""",INR,http://assets.myntassets.com/assets/images/186...,...,"{""1_star"":24,""2_stars"":8,""3_stars"":22,""4_stars...",NaN,NaN,"[{""size"":""Medium""}]",NaN,NaN,"[{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",yoga-mats

In [5]:
data.shape

(1000, 24)

In [6]:
data.size

24000

In [7]:
data.describe()

         product_id     rating  ratings_count  initial_price    discount
count  1.000000e+03  1000.0000    1000.000000     1000.00000  879.000000
mean   1.713437e+07     3.6215      76.691000     2723.24100   53.503982
std    3.813766e+06     1.3744     241.114263     2408.69736   18.029201
min    5.868460e+05     0.0000       0.000000      249.00000    1.000000
25%    1.511501e+07     3.7000       7.000000     1399.00000   44.000000
50%    1.820890e+07     4.1000      17.000000     1999.00000   56.000000
75%    1.902737e+07     4.3000      58.000000     3299.00000   66.000000
max    2.274707e+07     5.0000    4441.000000    22199.00000   88.000000

In [8]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 24 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   product_id              1000 non-null   int64
 1   title                   1000 non-null   str
 2   product_description     1000 non-null   str
 3   rating                  1000 non-null   float64
 4   ratings_count           1000 non-null   int64
 5   initial_price           1000 non-null   int64
 6   discount                879 non-null    float64
 7   final_price             1000 non-null   str
 8   currency                1000 non-null   str
 9   images                  1000 non-null   str
 10  delivery_options        1000 non-null   str
 11  product_details         1000 non-null   str
 12  breadcrumbs             1000 non-null   str
 13  product_specifications  1000 non-null   str
 14  amount_of_stars         1000 non-null   str
 15  what_customers_said     427 non-null    str
 16  seller_name             699 non-null    str
 17  sizes                   1000 non-null   str
 18  videos                  219 non-null    str
 19  seller_information      699 non-null    str
 20  variations              438 non-null    str
 21  best_offer              1000 non-null   str
 22  more_offers             1000 non-null   str
 23  category                1000 non-null   str
dtypes: float64(2), int64(3), str(19)
memory usage: 187.6 KB

In [9]:
data.duplicated().sum()

np.int64(0)

In [10]:
data.isnull().sum()

product_id                  0
title                       0
product_description         0
rating                      0
ratings_count               0
initial_price               0
discount                  121
final_price                 0
currency                    0
images                      0
delivery_options            0
product_details             0
breadcrumbs                 0
product_specifications      0
amount_of_stars             0
what_customers_said       573
seller_name               301
sizes                       0
videos                    781
seller_information        301
variations                562
best_offer                  0
more_offers                 0
category                    0
dtype: int64

In [11]:
data.isna().sum()

product_id                  0
title                       0
product_description         0
rating                      0
ratings_count               0
initial_price               0
discount                  121
final_price                 0
currency                    0
images                      0
delivery_options            0
product_details             0
breadcrumbs                 0
product_specifications      0
amount_of_stars             0
what_customers_said       573
seller_name               301
sizes                       0
videos                    781
seller_information        301
variations                562
best_offer                  0
more_offers                 0
category                    0
dtype: int64

In [12]:
data_check = pd.read_csv("E:\\celebal internship\\week 1\\datas\\archive\\bath-towels.csv")

In [13]:
data_check

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,...,amount_of_stars,what_customers_said,seller_name,sizes,videos,seller_information,variations,best_offer,more_offers,category
0,19851824,AVI Living,Grey Solid 500 GSM Pure Cotton Bath Towel,4.0,5,1399.0,65.0,"""₹1,399.00""",INR,http://assets.myntassets.com/assets/images/198...,...,"{""1_star"":0,""2_stars"":1,""3_stars"":0,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]",NaN,NaN,"[{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",bath-towels

In [14]:
df = data.copy()

In [17]:
column = df.columns

In [18]:
column

Index(['product_id', 'title', 'product_description', 'rating', 'ratings_count',
       'initial_price', 'discount', 'final_price', 'currency', 'images',
       'delivery_options', 'product_details', 'breadcrumbs',
       'product_specifications', 'amount_of_stars', 'what_customers_said',
       'seller_name', 'sizes', 'videos', 'seller_information', 'variations',
       'best_offer', 'more_offers', 'category'],
      dtype='str')

In [19]:
df["breadcrumbs"]

0      [{"name":"Accessories","url":"https://www.mynt...
1      [{"name":"Accessories","url":"https://www.mynt...
2      [{"name":"Accessories","url":"https://www.mynt...
3      [{"name":"Accessories","url":"https://www.mynt...
4      [{"name":"Men","url":"https://www.myntra.com/m...
                             ...
995    [{"name":"Accessories","url":"https://www.mynt...
996    [{"name":"Accessories","url":"https://www.mynt...
997    [{"name":"Accessories","url":"https://www.mynt...
998    [{"name":"Accessories","url":"https://www.mynt...
999    [{"name":"Unisex","url":"https://www.myntra.co...
Name: breadcrumbs, Length: 1000, dtype: str

In [21]:
df.drop(columns= ["product_details" , "videos" , "what_customers_said" , "product_specifications" , "seller_name" , "images" , "seller_information" , "breadcrumbs" , "best_offer" , "more_offers" ], inplace = True)

In [22]:
df.shape

(1000, 14)

In [25]:
df['final_rating'] = df['ratings_count'] * df["rating"]

In [26]:
df.drop(columns = ["ratings_count" , "rating"] , inplace = True)

In [29]:
df["quantity"] = data["ratings_count"] * 2
# assuming only 50% of buyers gave ratings to product , so the quantity sold would be number of ratings *2

In [30]:
df

,product_id,title,product_description,initial_price,discount,final_price,currency,delivery_options,amount_of_stars,sizes,variations,category,final_rating,quantity
0,8376765,Lino Perros,Women Navy Blue Solid Backpack,3995,58.0,"""₹3,995.00""",INR,"[""100% Original Products"",""Pay on delivery mig...","{""1_star"":2,""2_stars"":0,""3_stars"":3,""4_stars"":...","[{""size"":""Onesize""}]",[{}],backpacks,57.0,30
1,9136281,Tommy Hilfiger,Unisex Navy Blue Striped Backpack,2899,35.0,"""₹2,899.00""",INR,"[""100% Original Products"",""Pay on delivery mig...","{""1_star"":3,""2_stars"":4,""3_stars"":2,""4_stars"":...","[{""size"":""Onesize""}]","[{},{}]",backpacks,301.5,134
2,17633752,Lavie,Aries Women Pink Mini Backpack,2999,65.0,"""₹2,999.00""",INR,"[""100% Original Products"",""Pay on delivery mig...","{""1_star"":9,""2_stars"":5,""3_stars"":10,""4_stars""...","[{""size"":""S""}]","[{},{},{},{},{},{}]",backpacks,994.4,452
3,1376949,F Gear,Unisex Navy & Grey Printed Burner Backpack,1675,52.0,"""₹1,675.00""",INR,"[""100% Original Products"",""Pay on delivery mig...","{""1_star"":33,""2_stars"":21,""3_stars"":69,""4_star...","[{""size"":""Onesize""}]",NaN,backpacks,4628.8,2104
4,13939916,MYTRIDENT,Men Blue Solid Bath Robe,2899,17.0,"""₹2,899.00""",INR,"[""100% Original Products"",""Pay on delivery mig...","{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...","[{""size"":""M"",""value"":""45.0in"",""value_name"":""Fr...","[{},{},{},{},{},{},{},{},{},{},{},{},{},{}]",bath-robe,56.4,24
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,13698258,KREDO,Men FORTE Silver Automatic Skeleton Analogue W...,11890,50.0,"""₹11,890.00""",INR,"[""100% Original Products"",""Pay on delivery mig...","{""1_star"":3,""2_stars"":0,""3_stars"":2,""4_stars"":...","[{""size"":""Onesize""}]",NaN,watches,38.5,22
996,16896006,GUESS,Women White Patterned Dial & White Straps Anal...,8900,45.0,"""₹8,900.00""",INR,"[""100% Original Products"",""Pay on delivery mig...","{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...","[{""size"":""Onesize""}]",NaN,watches,110.0,44
997,1708108,GIORDANO,Women Rose Gold-Toned Mirrored Analogue Watch ...,7950,50.0,"""₹7,950.00""",INR,"[""100% Original Products"",""Pay on delivery mig...","{""1_star"":2,""2_stars"":1,""3_stars"":0,""4_stars"":...","[{""size"":""Onesize""}]","[{},{},{},{},{},{},{},{}]",watches,14.0,10
998,19280114,Fastrack,Men Black Brass Dial & Black Stainless Steel S...,3295,20.0,"""₹2,636.00""",INR,"[""100% Original Products"",""Pay on delivery mig...","{""1_star"":1,""2_stars"":2,""3_stars"":0,""4_stars"":...","[{""size"":""Onesize""}]",NaN,watches,73.1,34
999,18601682,BOLDFIT,Purple Textured Yoga Mat,699,31.0,"""₹699.00""",INR,"[""100% Original Products"",""Pay on delivery mig...","{""1_star"":24,""2_stars"":8,""3_stars"":22,""4_stars...","[{""size"":""Medium""}]","[{},{},{},{}]",yoga-mats,611.8,322

In [31]:
df.drop(columns = ["product_description" , "delivery_options" , "sizes" , "variations" ] , inplace = True)

In [32]:
df

,product_id,title,initial_price,discount,final_price,currency,amount_of_stars,category,final_rating,quantity
0,8376765,Lino Perros,3995,58.0,"""₹3,995.00""",INR,"{""1_star"":2,""2_stars"":0,""3_stars"":3,""4_stars"":...",backpacks,57.0,30
1,9136281,Tommy Hilfiger,2899,35.0,"""₹2,899.00""",INR,"{""1_star"":3,""2_stars"":4,""3_stars"":2,""4_stars"":...",backpacks,301.5,134
2,17633752,Lavie,2999,65.0,"""₹2,999.00""",INR,"{""1_star"":9,""2_stars"":5,""3_stars"":10,""4_stars""...",backpacks,994.4,452
3,1376949,F Gear,1675,52.0,"""₹1,675.00""",INR,"{""1_star"":33,""2_stars"":21,""3_stars"":69,""4_star...",backpacks,4628.8,2104
4,13939916,MYTRIDENT,2899,17.0,"""₹2,899.00""",INR,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",bath-robe,56.4,24
...,...,...,...,...,...,...,...,...,...,...
995,13698258,KREDO,11890,50.0,"""₹11,890.00""",INR,"{""1_star"":3,""2_stars"":0,""3_stars"":2,""4_stars"":...",watches,38.5,22
996,16896006,GUESS,8900,45.0,"""₹8,900.00""",INR,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",watches,110.0,44
997,1708108,GIORDANO,7950,50.0,"""₹7,950.00""",INR,"{""1_star"":2,""2_stars"":1,""3_stars"":0,""4_stars"":...",watches,14.0,10
998,19280114,Fastrack,3295,20.0,"""₹2,636.00""",INR,"{""1_star"":1,""2_stars"":2,""3_stars"":0,""4_stars"":...",watches,73.1,34
999,18601682,BOLDFIT,699,31.0,"""₹699.00""",INR,"{""1_star"":24,""2_stars"":8,""3_stars"":22,""4_stars...",yoga-mats,611.8,322

In [33]:
df.drop(columns = ["amount_of_stars"] , inplace =True)

In [37]:
df["final_price"] = df["final_price"].str.replace("₹" , "" , regex = False)
df["final_price"] = df["final_price"].str.replace("," , "" , regex = False)
df['final_price'] = df['final_price'].str.split(".").str[0]
df["final_price"] = df["final_price"].str.replace('"', '', regex=False)
df["final_price"] = df["final_price"].astype(int)

In [38]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 9 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   product_id     1000 non-null   int64
 1   title          1000 non-null   str
 2   initial_price  1000 non-null   int64
 3   discount       879 non-null    float64
 4   final_price    1000 non-null   int64
 5   currency       1000 non-null   str
 6   category       1000 non-null   str
 7   final_rating   1000 non-null   float64
 8   quantity       1000 non-null   int64
dtypes: float64(2), int64(4), str(3)
memory usage: 70.4 KB

In [39]:
num_differences = (df["final_price"] != df["initial_price"]).sum()
print(f"There are {num_differences} rows with different values.")

There are 637 rows with different values.

In [40]:
differences = df[df["final_price"] != df["initial_price"]]

# Display the rows that don't match
print(differences[["final_price", "initial_price"]])

     final_price  initial_price
11           865           3329
12           404           1499
18           223           1399
19          1799           2999
20           699            999
..           ...            ...
986         1596           1995
991         3266           6950
992         3235           3595
993          799           1599
998         2636           3295

[637 rows x 2 columns]

In [41]:
df["currency"].nunique()

1

In [42]:
df.drop(columns = ["currency" , "title"] , inplace = True)

In [43]:
df

,product_id,initial_price,discount,final_price,category,final_rating,quantity
0,8376765,3995,58.0,3995,backpacks,57.0,30
1,9136281,2899,35.0,2899,backpacks,301.5,134
2,17633752,2999,65.0,2999,backpacks,994.4,452
3,1376949,1675,52.0,1675,backpacks,4628.8,2104
4,13939916,2899,17.0,2899,bath-robe,56.4,24
...,...,...,...,...,...,...,...
995,13698258,11890,50.0,11890,watches,38.5,22
996,16896006,8900,45.0,8900,watches,110.0,44
997,1708108,7950,50.0,7950,watches,14.0,10
998,19280114,3295,20.0,2636,watches,73.1,34
999,18601682,699,31.0,699,yoga-mats,611.8,322

In [44]:
df["price_after_discount"] = df["final_price"] - df["discount"]
df["original_rating_quantity"] = df["quantity"]/2

In [45]:
df.duplicated().sum()

np.int64(0)

In [46]:
df["final_price"].isna().sum()

np.int64(0)

In [47]:
df["quantity"].isna().sum()

np.int64(0)

In [48]:
df["quantity"].isnull().sum()

np.int64(0)

In [49]:
df["final_price"].isnull().sum()

np.int64(0)

In [50]:
df["assumed_quantity"] = df["quantity"]
df.columns

Index(['product_id', 'initial_price', 'discount', 'final_price', 'category',
       'final_rating', 'quantity', 'price_after_discount',
       'original_rating_quantity', 'assumed_quantity'],
      dtype='str')

In [51]:
df.drop(columns = ["quantity" , "final_rating" , "category" ] , inplace = True)

In [52]:
df["total_amount1"] = df["initial_price"] * df["original_rating_quantity"]
df["total_amount2"] = df["initial_price"] * df["assumed_quantity"]
df["total_amount3"] = df["final_price"] * df["original_rating_quantity"]
df["total_amount4"] = df["final_price"] * df["assumed_quantity"]

In [53]:
df

,product_id,initial_price,discount,final_price,price_after_discount,original_rating_quantity,assumed_quantity,total_amount1,total_amount2,total_amount3,total_amount4
0,8376765,3995,58.0,3995,3937.0,15.0,30,59925.0,119850,59925.0,119850
1,9136281,2899,35.0,2899,2864.0,67.0,134,194233.0,388466,194233.0,388466
2,17633752,2999,65.0,2999,2934.0,226.0,452,677774.0,1355548,677774.0,1355548
3,1376949,1675,52.0,1675,1623.0,1052.0,2104,1762100.0,3524200,1762100.0,3524200
4,13939916,2899,17.0,2899,2882.0,12.0,24,34788.0,69576,34788.0,69576
...,...,...,...,...,...,...,...,...,...,...,...
995,13698258,11890,50.0,11890,11840.0,11.0,22,130790.0,261580,130790.0,261580
996,16896006,8900,45.0,8900,8855.0,22.0,44,195800.0,391600,195800.0,391600
997,1708108,7950,50.0,7950,7900.0,5.0,10,39750.0,79500,39750.0,79500
998,19280114,3295,20.0,2636,2616.0,17.0,34,56015.0,112030,44812.0,89624
999,18601682,699,31.0,699,668.0,161.0,322,112539.0,225078,112539.0,225078

In [55]:
df.to_csv("datas\week1_assignment_submission_data.csv" , index=False)

<>:1: SyntaxWarning: "\w" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\w"? A raw string is also an option.
<>:1: SyntaxWarning: "\w" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\w"? A raw string is also an option.
C:\Users\DELL\AppData\Local\Temp\ipykernel_14512\2849031543.py:1: SyntaxWarning: "\w" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\w"? A raw string is also an option.
  df.to_csv("datas\week1_assignment_submission_data.csv" , index=False)